# Generated by Django 2.2.6 on 2020-11-26 10:13

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyOmnibusRule',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(
                    default=False, verbose_name='是否启用')),
                ('title', models.CharField(
                    max_length=128, null=True, verbose_name='规则名称')),
                ('describe', models.TextField(null=True, verbose_name='规则描述')),
                ('datetime_create', models.DateTimeField(auto_now_add=True,
                                                         help_text='自动创建,无需人工填写', null=True, verbose_name='创建时间')),
                ('datetime_modify', models.DateTimeField(auto_now=True,
                                                         help_text='自动创建,无需人工填写', null=True, verbose_name='更新时间')),
                ('rule', jsonfield.fields.JSONField(verbose_name='规则(JSON格式)')),
            ],
            options={
                'verbose_name': '综合类告警聚合规则',
            },
        ),
        migrations.CreateModel(
            name='EmergencyOvertimeRule',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enable', models.BooleanField(
                    default=False, verbose_name='是否启用')),
                ('title', models.CharField(
                    max_length=128, null=True, verbose_name='规则名称')),
                ('describe', models.TextField(null=True, verbose_name='规则描述')),
                ('datetime_create', models.DateTimeField(auto_now_add=True,
                                                         help_text='自动创建,无需人工填写', null=True, verbose_name='创建时间')),
                ('datetime_modify', models.DateTimeField(auto_now=True,
                                                         help_text='自动创建,无需人工填写', null=True, verbose_name='更新时间')),
                ('rule', jsonfield.fields.JSONField(verbose_name='规则(JSON格式)')),
            ],
            options={
                'verbose_name': '交易类告警聚合规则',
            },
        ),
    ]
