# Generated by Django 2.2.6 on 2020-11-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StaffName', models.CharField(blank=True, max_length=32, null=True, verbose_name='姓名')),
                ('OrgName', models.CharField(blank=True, max_length=128, null=True, verbose_name='部门')),
                ('Company', models.CharField(blank=True, max_length=128, null=True, verbose_name='公司')),
                ('Mobile', models.CharField(blank=True, max_length=16, null=True, verbose_name='手机号')),
            ],
            options={
                'verbose_name': 'ITIL人员信息',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.SmallIntegerField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], null=True, verbose_name='事件级别')),
                ('number', models.CharField(blank=True, max_length=128, null=True, verbose_name='事件单号')),
                ('dealer', models.CharField(blank=True, max_length=128, verbose_name='处理人')),
                ('remark', models.TextField(blank=True, verbose_name='处理建议')),
            ],
            options={
                'verbose_name': '事件',
            },
        ),
        migrations.CreateModel(
            name='OffsetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128, verbose_name='主题')),
                ('partition', models.IntegerField(verbose_name='分区')),
                ('offset', models.IntegerField(verbose_name='偏移量')),
                ('time_into_db', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyOvertimeGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '未处理'), (1, '已通知 待处理'), (2, '已处理')], default=0, verbose_name='告警状态')),
                ('storage_datetime', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('system_cn', models.CharField(blank=True, max_length=128, null=True, verbose_name='告警系统/来源(中文 根据system去cmdb中查询)')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='最后时间')),
                ('error_count', models.IntegerField(blank=True, null=True, verbose_name='超时数量(笔数)')),
                ('key', models.CharField(blank=True, max_length=128, null=True, verbose_name='唯一标识')),
                ('qudao_cn', models.CharField(blank=True, max_length=256, null=True, verbose_name='渠道翻译')),
                ('server_cn', models.CharField(blank=True, max_length=256, null=True, verbose_name='服务码翻译')),
                ('branch_cn', models.CharField(blank=True, max_length=256, null=True, verbose_name='机构码翻译')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='交易码')),
                ('code_cn', models.CharField(blank=True, max_length=256, null=True, verbose_name='交易码翻译')),
                ('rtcode_cn', models.CharField(blank=True, max_length=256, null=True, verbose_name='返回码翻译')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.Event', verbose_name='所属事件')),
            ],
            options={
                'verbose_name': '交易类告警聚合',
            },
        ),
        migrations.CreateModel(
            name='EmergencyOvertime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checkbox', models.BooleanField(default=False)),
                ('hash_id', models.CharField(max_length=32, null=True, verbose_name='哈希值')),
                ('storage_timestamp', models.CharField(blank=True, max_length=18, null=True, verbose_name='入库时间戳')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='最后时间')),
                ('error_count', models.IntegerField(null=True, verbose_name='超时数量(笔数)')),
                ('system', models.CharField(blank=True, max_length=256, null=True, verbose_name='告警渠道(来源)')),
                ('system_cn', models.CharField(blank=True, max_length=128, null=True, verbose_name='告警系统(来源)翻译')),
                ('qudao', models.CharField(blank=True, max_length=128, null=True, verbose_name='渠道')),
                ('qudao_cn', models.CharField(blank=True, max_length=256, null=True, verbose_name='渠道翻译')),
                ('server', models.CharField(blank=True, max_length=128, null=True, verbose_name='服务码')),
                ('server_cn', models.CharField(blank=True, max_length=256, null=True, verbose_name='服务码翻译')),
                ('branch_cn', models.CharField(blank=True, max_length=256, null=True, verbose_name='机构码翻译')),
                ('code', models.CharField(blank=True, max_length=128, null=True, verbose_name='交易码')),
                ('code_cn', models.CharField(blank=True, max_length=128, null=True, verbose_name='交易码翻译')),
                ('rtcode', models.CharField(blank=True, max_length=128, null=True, verbose_name='返回码')),
                ('rtcode_cn', models.CharField(blank=True, max_length=256, null=True, verbose_name='返回码翻译')),
                ('key', models.CharField(max_length=128, verbose_name='唯一标识')),
                ('route', models.CharField(blank=True, max_length=256, null=True, verbose_name='路由')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.EmergencyOvertimeGroup', verbose_name='交易类告警聚合ID')),
            ],
            options={
                'verbose_name': '交易类告警',
            },
        ),
        migrations.CreateModel(
            name='EmergencyOmnibusGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, '未处理'), (1, '已通知 待处理'), (2, '已处理')], default=0, verbose_name='告警状态')),
                ('storage_datetime', models.DateTimeField(blank=True, null=True, verbose_name='入库时间')),
                ('system_cn', models.CharField(blank=True, max_length=128, null=True, verbose_name='告警系统/来源(中文 根据system去cmdb中查询)')),
                ('occurrence_time', models.TimeField(blank=True, null=True, verbose_name='告警时间')),
                ('summary', models.TextField(blank=True, verbose_name='告警描述')),
                ('contact', models.TextField(blank=True, verbose_name='联系人')),
                ('level', models.SmallIntegerField(blank=True, choices=[(10, '提示'), (20, '关注'), (40, '严重,'), (50, '高危'), (0, '其他')], default=10, verbose_name='告警分级')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='emergency.Event', verbose_name='所属事件')),
            ],
            options={
                'verbose_name': '综合类告警聚合',
            },
        ),
        migrations.CreateModel(
            name='EmergencyOmnibus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checkbox', models.BooleanField(default=False)),
                ('hash_id', models.CharField(max_length=32, null=True, verbose_name='哈希值')),
                ('occurrence_time', models.TimeField(blank=True, null=True, verbose_name='告警时间')),
                ('storage_timestamp', models.CharField(blank=True, max_length=18, null=True, verbose_name='入库时间戳')),
                ('summary', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警描述')),
                ('mastertid', models.CharField(blank=True, max_length=128, null=True, verbose_name='告警事件的告警组')),
                ('contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人')),
                ('is_import', models.NullBooleanField(verbose_name='影响是否重要')),
                ('operation', models.SmallIntegerField(blank=True, choices=[(0, '应用'), (1, '中间件'), (2, '数据库'), (3, '操作系统'), (4, '其他')], verbose_name='事件类型')),
                ('swapiden', models.CharField(blank=True, max_length=128, null=True, verbose_name='告警类型')),
                ('tally', models.IntegerField(blank=True, null=True, verbose_name='告警次数')),
                ('ntlogged', models.CharField(blank=True, max_length=256, null=True, verbose_name='')),
                ('dep', models.IntegerField(blank=True, null=True, verbose_name='告警机构(9999是总行)')),
                ('first_occurrence', models.CharField(blank=True, max_length=18, null=True, verbose_name='第一次告警时间戳')),
                ('last_occurrence', models.CharField(blank=True, max_length=18, null=True, verbose_name='最后一次告警时间戳')),
                ('severity', models.IntegerField(blank=True, null=True, verbose_name='告警级别')),
                ('server_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='告警来源')),
                ('bapp_system', models.CharField(blank=True, max_length=128, null=True, verbose_name='告警机器所属系统')),
                ('level', models.SmallIntegerField(blank=True, choices=[(10, '提示'), (20, '关注'), (40, '严重,'), (50, '高危'), (0, '其他')], default=10, verbose_name='告警分级')),
                ('operator', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('jyresult', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('node', models.GenericIPAddressField(null=True, verbose_name='告警机器IP')),
                ('confirm_msg', models.CharField(blank=True, max_length=255, null=True, verbose_name='告警事件处理信息(预留字段 不建议存值 留空即可）')),
                ('system', models.CharField(blank=True, max_length=128, null=True, verbose_name='告警系统(来源)')),
                ('system_cn', models.CharField(blank=True, max_length=128, null=True, verbose_name='告警系统(来源)翻译')),
                ('acknowledged', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('identifier', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergency.EmergencyOmnibusGroup', verbose_name='综合类告警聚合ID')),
            ],
            options={
                'verbose_name': '综合类告警',
            },
        ),
    ]
