# Generated by Django 2.2.6 on 2020-11-20 09:07

from django.db import migrations, models
# import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyomnibus',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='联系人'),
        ),
    ]
