# Generated by Django 2.2.6 on 2020-11-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0003_auto_20201123_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailedOffset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128, verbose_name='主题')),
                ('partition', models.IntegerField(verbose_name='分区')),
                ('offset', models.IntegerField(verbose_name='偏移量')),
                ('is_success', models.BooleanField(default=False, verbose_name='是否成功写入')),
                ('time_into_db', models.DateTimeField(auto_now=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '记录抽象表',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FaultLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=128, verbose_name='主题')),
                ('partition', models.IntegerField(verbose_name='分区')),
                ('offset', models.IntegerField(verbose_name='偏移量')),
                ('value', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('time_into_db', models.DateTimeField(auto_now=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '记录抽象表',
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='OffsetModel',
        ),
    ]
