# Generated by Django 2.2.6 on 2020-12-22 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0004_auto_20201125_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyomnibus',
            name='confirm_msg',
            field=models.TextField(
                blank=True, max_length=255, null=True, verbose_name='告警事件处理信息'),
        ),
        migrations.AlterField(
            model_name='emergencyomnibus',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(
                10, '提示'), (20, '关注'), (40, '严重'), (50, '高危'), (0, '其他')], default=10, verbose_name='告警分级'),
        ),
        migrations.AlterField(
            model_name='emergencyomnibusgroup',
            name='level',
            field=models.SmallIntegerField(blank=True, choices=[(
                10, '提示'), (20, '关注'), (40, '严重'), (50, '高危'), (0, '其他')], default=10, verbose_name='告警分级'),
        ),
        migrations.AlterField(
            model_name='emergencyomnibusgroup',
            name='system_cn',
            field=models.CharField(blank=True, help_text='根据system去cmdb中查询',
                                   max_length=128, null=True, verbose_name='告警系统/来源'),
        ),
        migrations.AlterField(
            model_name='emergencyovertimegroup',
            name='system_cn',
            field=models.CharField(blank=True, help_text='根据system去cmdb中查询',
                                   max_length=128, null=True, verbose_name='告警系统/来源'),
        ),
        migrations.AddField(
            model_name='employee',
            name='Account',
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name='账号'),
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True,
                                          max_length=32, null=True, verbose_name='系统名称')),
                ('managers', models.ManyToManyField(
                    blank=True, to='emergency.Employee')),
            ],
        ),
    ]
